services:
  db:
    image: postgres:16
    container_name: lifee-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: lifee
      POSTGRES_PASSWORD: lifee_password_change_me
      POSTGRES_DB: lifee_db
    ports:
      - "5432:5432" # pour dev local; en prod tu peux retirer pour ne pas exposer
    volumes:
      - lifee_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lifee -d lifee_db"]
      interval: 5s
      timeout: 3s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4
    container_name: lifee-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lifee.local
      PGADMIN_DEFAULT_PASSWORD: change_me
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  lifee_pg_data:
